//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings_TestsApplication : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_TestsApplication defaultInstance = ((Settings_TestsApplication)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_TestsApplication())));
        
        public static Settings_TestsApplication Default {
            get {
                return defaultInstance;
            }
        }
    }
}
